export interface Parcel {
  id: number;
  parcelNumber: string;
  entityId: string;
  username: string;
  senderName: string;
  receiverName: string;
  senderPhoneNumber: string;
  receiverPhoneNumber: string;
  sourceName: string;
  destinationName: string;
  parcelStatus:"REGISTERED" |  "IN_TRANSIT" | "ARRIVED" | "COLLECTED" | "CANCELLED" ;
  paymentStatus: "PAID" | "UNPAID" | "PENDING";
  paymentMethod: "CASH" | "CASHLESS";
  fleetNo: string;
  amount: number;
  dispatchedAt: string | null;
  arrivedAt: string | null;
  receivedBy: string | null;
  pickedAt: string | null;
  pickedBy: string | null;
  createdAt: string;
  updatedAt: string | null;
  description: string;
  value: string;
  lastMile: string;
  expense: number | null;
  expenseDescription: string | null;
  serviceCharge: number;
  mpesaReceiptNumber: string | null;
}
